
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-github
  description: Esto es un ejemplo
  tags:
    - angular
    - react
spec:
  owner: guests
  type: service
  lifecycle: production
  system: ejemplo
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test3-github
  description: test
spec:
  owner: guests
  type: openapi
  lifecycle: production
  system: test
  definition: test
