apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test2-github
  description: Es otro test
  tags:
    - react
    - fluxcd
spec:
  owner: guests
  type: openapi
  lifecycle: experimental
  definition: Es un test
